import React, { useState, useEffect, useCallback } from 'react';
import {
    AppView,
    PowerStudioProject,
    UGCStudioProject,
    VoiceOverStudioProject,
    PromptStudioProject,
    VideoStudioProject,
    CampaignStudioProject,
    ControllerStudioProject,
    BrandingStudioProject,
    ProjectBase,
    ImageFile,
    PlanStudioProject,
    CreatorStudioProject,
    InfluencerStudioProject,
    EditStudioProject,
    PhotoshootDirectorProject,
    CopywriterStudioProject
} from './types';
import { supabase, getUserCredits } from './lib/supabase';
import UGCStudio from './components/UGCStudio';
import VoiceOverStudio from './components/VoiceOverStudio';
import PromptStudio from './components/PromptStudio';
import VideoStudio from './components/VideoStudio';
import PowerStudio from './components/PowerStudio';
import CampaignStudio from './components/CampaignStudio';
import ControllerStudio from './components/ControllerStudio';
import BrandingStudio from './components/BrandingStudio';
import PlanStudio from './components/PlanStudio';
import CreatorStudio from './components/CreatorStudio';
import InfluencerStudio from './components/InfluencerStudio';
import EditStudio from './components/EditStudio';
import PhotoshootDirector from './components/PhotoshootDirector';
import CopywriterStudio from './components/CopywriterStudio';

import ThemeSwitcher from './components/ThemeSwitcher';
import CreditsDisplay from './components/CreditsDisplay';
import LandingPage from './components/LandingPage';
import TabBar from './components/TabBar';

// Initial States
const initialUGC: UGCStudioProject = {
    id: 'demo-ugc', name: 'UGC Studio', productImages: [], selectedScenarios: [], results: [],
    isGenerating: false, error: null
};

const initialVoice: VoiceOverStudioProject = {
    id: 'demo-voice', name: 'Voice Studio', text: '', styleInstructions: '', selectedVoice: 'ar-SA-Standard-A',
    voiceGenderFilter: 'All', generatedAudio: null, history: [], isLoading: false, isPlaying: false,
    previewLoadingVoice: null, previewPlayingVoice: null, error: null
};

const initialPrompt: PromptStudioProject = {
    id: 'demo-prompt', name: 'Prompt Studio', images: [], instructions: '', generatedPrompt: null,
    history: [], isLoading: false, isUploading: false, error: null
};

const initialVideo: VideoStudioProject = {
    id: 'demo-video', name: 'Video Studio', prompt: '', isGenerating: false, videoUrl: null,
    progress: 0, statusText: '', error: null
};

const initialPower: PowerStudioProject = {
    id: 'demo-power', name: 'Power Studio', productImages: [], goal: '', targetMarket: '', dialect: 'Gulf',
    isGenerating: false, currentStep: '', progress: 0, result: null, error: null
};

const initialCampaign: CampaignStudioProject = {
    id: 'demo-campaign', name: 'Campaign Studio', productImages: [], productAnalysis: null, isAnalyzing: false,
    selectedMood: 'Creative', customPrompt: '', customIdeas: [], mode: 'auto', results: [],
    isGenerating: false, isUploading: false, error: null
};

const initialController: ControllerStudioProject = {
    id: 'demo-controller', name: 'Controller Studio', sourceImages: [], generatedImage: null,
    sliders: [
        { id: 'smile', label: 'Smile', value: 0, min: -1, max: 1, step: 0.1, category: 'Face' },
        { id: 'age', label: 'Age', value: 0, min: -1, max: 1, step: 0.1, category: 'Face' },
        { id: 'head_yaw', label: 'Head Turn', value: 0, min: -1, max: 1, step: 0.1, category: 'Head' },
        { id: 'head_pitch', label: 'Head Tilt', value: 0, min: -1, max: 1, step: 0.1, category: 'Head' },
    ],
    activeCategory: 'Face', isGenerating: false, isUploading: false, history: [], error: null
};

const initialBranding: BrandingStudioProject = {
    id: 'demo-branding', name: 'Branding Studio', logos: [], results: [], colors: [],
    isGenerating: false, isUploading: false, isAnalyzing: false, aspectRatio: '1:1', error: null
};

const initialPlan: PlanStudioProject = {
    id: 'demo-plan', name: 'Plan Studio', productImages: [], prompt: '', targetMarket: '', dialect: 'Modern',
    ideas: [], isGeneratingPlan: false, isUploading: false, categoryAnalysis: null, isAnalyzingCategory: false, error: null
};

const initialCreator: CreatorStudioProject = {
    id: 'demo-creator', name: 'Creator Studio', productImages: [], styleImages: [], generatedImage: null,
    history: [], options: { lightingStyle: 'Studio Light', cameraPerspective: 'Front View' },
    prompt: '', isPromptAutoGenerated: false, isLoading: false, error: null, styleDescription: null,
    isAnalyzingStyle: false, translatedPrompt: null, isTranslating: false, isEditing: false, uploadingTarget: null
};

const initialInfluencer: InfluencerStudioProject = {
    id: 'demo-influencer', name: 'Influencer Studio', productImages: [], selectedPersonas: [], results: [],
    isGenerating: false, error: null
};

const initialEdit: EditStudioProject = {
    id: 'demo-edit', name: 'Edit Studio', baseImages: [], localTexts: {}, committedTexts: {}, globalLayers: [],
    adjustments: { sharpness: 0, lut: 'none' }, isUploading: false
};

const initialPhotoshoot: PhotoshootDirectorProject = {
    id: 'demo-photoshoot', name: 'Photoshoot Director', productImages: [], selectedShotTypes: [], results: [],
    isGenerating: false, isUploading: false, customStylePrompt: '', error: null
};

const initialCopywriter: CopywriterStudioProject = {
    id: 'demo-copywriter', name: 'Copywriter Studio', productName: '', features: '', targetAudience: '',
    results: [], isGenerating: false, error: null
};

const App = () => {
    const [view, setView] = useState<AppView>('landing');
    const [user, setUser] = useState({ id: 'demo-user', email: 'demo@ebdaapro.com' });
    const [credits, setCredits] = useState(999);
    const [theme, setTheme] = useState('dark');

    // Project State
    const [activeProjectIndex, setActiveProjectIndex] = useState(0);
    const [projects, setProjects] = useState<ProjectBase[]>([
        { id: 'p1', name: 'Power Studio' },
        { id: 'p2', name: 'UGC Studio' },
        { id: 'p3', name: 'Voice Studio' },
        { id: 'p4', name: 'Video Studio' },
        { id: 'p5', name: 'Campaign Studio' },
        { id: 'p6', name: 'Branding Studio' },
        { id: 'p7', name: 'Prompt Studio' },
        { id: 'p8', name: 'Controller Studio' },
        { id: 'p9', name: 'Plan Studio' },
        { id: 'p10', name: 'Creator Studio' },
        { id: 'p11', name: 'Influencer Studio' },
        { id: 'p12', name: 'Edit Studio' },
        { id: 'p13', name: 'Photoshoot Director' },
        { id: 'p14', name: 'Copywriter Studio' }
    ]);

    // Detailed Project States
    const [ugcProject, setUGCProject] = useState<UGCStudioProject>(initialUGC);
    const [voiceProject, setVoiceProject] = useState<VoiceOverStudioProject>(initialVoice);
    const [promptProject, setPromptProject] = useState<PromptStudioProject>(initialPrompt);
    const [powerProject, setPowerProject] = useState<PowerStudioProject>(initialPower);
    const [campaignProject, setCampaignProject] = useState<CampaignStudioProject>(initialCampaign);
    const [controllerProject, setControllerProject] = useState<ControllerStudioProject>(initialController);
    const [brandingProject, setBrandingProject] = useState<BrandingStudioProject>(initialBranding);
    const [planProject, setPlanProject] = useState<PlanStudioProject>(initialPlan);
    const [creatorProject, setCreatorProject] = useState<CreatorStudioProject>(initialCreator);
    const [influencerProject, setInfluencerProject] = useState<InfluencerStudioProject>(initialInfluencer);
    const [editProject, setEditProject] = useState<EditStudioProject>(initialEdit);
    const [photoshootProject, setPhotoshootProject] = useState<PhotoshootDirectorProject>(initialPhotoshoot);
    const [copywriterProject, setCopywriterProject] = useState<CopywriterStudioProject>(initialCopywriter);

    const refreshCredits = async () => {
        if (user?.id) {
            const c = await getUserCredits(user.id);
            if (c !== null) setCredits(c);
        }
    };

    useEffect(() => {
        refreshCredits();
        // Refresh credits every 30 seconds
        const interval = setInterval(refreshCredits, 30000);
        return () => clearInterval(interval);
    }, [user]);

    const renderActiveStudio = () => {
        const activeProject = projects[activeProjectIndex];

        switch (activeProject.name) {
            case 'Power Studio':
                return <PowerStudio project={powerProject} setProject={setPowerProject} userId={user.id} refreshCredits={refreshCredits} />;
            case 'UGC Studio':
                return <UGCStudio project={ugcProject} setProject={setUGCProject} userId={user.id} refreshCredits={refreshCredits} />;
            case 'Voice Studio':
                return <VoiceOverStudio project={voiceProject} setProject={setVoiceProject} userId={user.id} refreshCredits={refreshCredits} />;
            case 'Video Studio':
                return <VideoStudio userId={user.id} refreshCredits={refreshCredits} />;
            case 'Campaign Studio':
                return <CampaignStudio project={campaignProject} setProject={setCampaignProject} userId={user.id} refreshCredits={refreshCredits} />;
            case 'Branding Studio':
                return <BrandingStudio project={brandingProject} setProject={setBrandingProject} userId={user.id} refreshCredits={refreshCredits} />;
            case 'Prompt Studio':
                return <PromptStudio project={promptProject} setProject={setPromptProject} />;
            case 'Controller Studio':
                return <ControllerStudio project={controllerProject} setProject={setControllerProject} />;
            case 'Plan Studio':
                return <PlanStudio project={planProject} setProject={setPlanProject} userId={user.id} refreshCredits={refreshCredits} />;
            case 'Creator Studio':
                return <CreatorStudio project={creatorProject} setProject={setCreatorProject} userId={user.id} refreshCredits={refreshCredits} />;
            case 'Influencer Studio':
                return <InfluencerStudio project={influencerProject} setProject={setInfluencerProject} userId={user.id} refreshCredits={refreshCredits} />;
            case 'Edit Studio':
                return <EditStudio project={editProject} setProject={setEditProject} />;
            case 'Photoshoot Director':
                return <PhotoshootDirector project={photoshootProject} setProject={setPhotoshootProject} userId={user.id} refreshCredits={refreshCredits} />;
            case 'Copywriter Studio':
                return <CopywriterStudio project={copywriterProject} setProject={setCopywriterProject} userId={user.id} refreshCredits={refreshCredits} />;
            default:
                return <div className="text-white text-center p-20">Select a studio to begin</div>;
        }
    };

    const handleAddTab = () => {
        // Logic to add new tabs could go here
        alert("New project creation would go here in full version");
    };

    const handleCloseTab = (index: number) => {
        if (projects.length <= 1) return;
        const newProjects = projects.filter((_, i) => i !== index);
        setProjects(newProjects);
        if (activeProjectIndex >= index && activeProjectIndex > 0) {
            setActiveProjectIndex(activeProjectIndex - 1);
        }
    };

    const handleGetStarted = () => {
        setView('suite_view');
    };

    if (view === 'landing') {
        return <LandingPage onGetStarted={handleGetStarted} />;
    }

    return (
        <div className={`min-h-screen bg-[rgb(var(--color-background-base-rgb))] text-[var(--color-text-base)] ${theme} font-tajawal`}>
            {/* Header */}
            <header className="fixed top-0 left-0 right-0 z-50 glass-card border-b border-white/5 px-6 py-4 flex items-center justify-between">
                <div className="flex items-center gap-4 cursor-pointer" onClick={() => setView('landing')}>
                    <div className="w-10 h-10 bg-indigo-600 rounded-xl flex items-center justify-center font-black text-white shadow-lg shadow-indigo-500/20">EB</div>
                    <h1 className="text-xl font-bold tracking-tight text-white hidden sm:block">Ebdaa Pro <span className="opacity-50 font-normal">Intelligence</span></h1>
                </div>

                <div className="flex items-center gap-4">
                    <CreditsDisplay credits={credits} />
                    <ThemeSwitcher theme={theme} setTheme={setTheme} />
                    <div className="w-10 h-10 rounded-full bg-gradient-to-br from-indigo-500 to-purple-600 border-2 border-white/10 shadow-xl"></div>
                </div>
            </header>

            {/* Main Content */}
            <div className="pt-24 px-4 pb-20 max-w-7xl mx-auto flex flex-col items-center">
                <TabBar
                    projects={projects}
                    activeProjectIndex={activeProjectIndex}
                    onSelectTab={setActiveProjectIndex}
                    onAddTab={handleAddTab}
                    onCloseTab={handleCloseTab}
                />

                <div className="w-full mt-6 animate-in slide-in-from-bottom-5 duration-500">
                    {renderActiveStudio()}
                </div>
            </div>
        </div>
    );
};

export default App;
