
export interface ImageFile {
    base64: string;
    mimeType: string;
    name: string;
}

export interface AudioFile {
    base64: string;
    name: string;
}

export type AspectRatio = '1:1' | '16:9' | '9:16' | '4:3' | '3:4' | '4:5';

export type LightingStyle = 'Natural Light' | 'Studio Light' | 'Golden Hour' | 'Blue Hour' | 'Cinematic' | 'Dramatic';

export type CameraPerspective = 'Front View' | 'Top View' | 'Side View' | '45° Angle' | 'Close-up' | 'Macro Shot';

/* Fix: Added ShotType exported type definition used across फोटोशूट components */
export type ShotType = string;

export interface CustomizationOptions {
    lightingStyle: LightingStyle;
    cameraPerspective: CameraPerspective;
}

export interface HistoryItem {
    image: ImageFile;
    prompt: string;
}

export interface ProjectBase {
    id: string;
    name: string;
}

export interface PowerStudioResult {
    analysis: string;
    visualPrompt: string;
    socialPlan: Array<{hook: string, caption: string, schedule: string, hashtags: string[]}>;
    reelsScripts: Array<{scene: string, visualDesc: string, audioOverlay: string}>;
    adCopies: Array<{platform: string, headline: string, body: string}>;
    voiceScript: string;
    visual: ImageFile;
    brandingColors: string[];
}

export interface PowerStudioProject extends ProjectBase {
    productImages: ImageFile[];
    goal: string;
    targetMarket: string;
    dialect: string;
    isGenerating: boolean;
    currentStep: string;
    progress: number;
    result: PowerStudioResult | null;
    error: string | null;
}

export interface UGCStudioProject extends ProjectBase {
    productImages: ImageFile[];
    selectedScenarios: string[];
    results: Array<{
        id: string;
        image: ImageFile | null;
        isLoading: boolean;
        scenario: string;
        error: string | null;
    }>;
    isGenerating: boolean;
    /* Fix: Added missing error property to UGCStudioProject */
    error: string | null;
}

export interface InfluencerStudioProject extends ProjectBase {
    productImages: ImageFile[];
    selectedPersonas: string[];
    results: Array<{
        id: string;
        image: ImageFile | null;
        isLoading: boolean;
        persona: string;
        error: string | null;
    }>;
    isGenerating: boolean;
    /* Fix: Added missing error property to InfluencerStudioProject */
    error: string | null;
}

export interface CreatorStudioProject extends ProjectBase {
    productImages: ImageFile[];
    styleImages: ImageFile[];
    generatedImage: ImageFile | null;
    history: HistoryItem[];
    options: CustomizationOptions;
    prompt: string;
    isPromptAutoGenerated: boolean;
    isLoading: boolean;
    error: string | null;
    styleDescription: string | null;
    isAnalyzingStyle: boolean;
    translatedPrompt: string | null;
    isTranslating: boolean;
    isEditing: boolean;
    uploadingTarget: 'product' | 'style' | null;
}

export interface PhotoshootResult {
    /* Fix: Updated to use ShotType */
    shotType: ShotType;
    image: ImageFile | null;
    isLoading: boolean;
    error: string | null;
    editPrompt: string;
    isEditing: boolean;
}

export interface PhotoshootDirectorProject extends ProjectBase {
    productImages: ImageFile[];
    /* Fix: Updated to use ShotType */
    selectedShotTypes: ShotType[];
    results: PhotoshootResult[];
    isGenerating: boolean;
    isUploading: boolean;
    customStylePrompt: string;
    error: string | null;
}

export interface BrandingResult {
    category: string;
    image: ImageFile | null;
    isLoading: boolean;
    error: string | null;
    editPrompt: string;
    isEditing: boolean;
}

export interface BrandingStudioProject extends ProjectBase {
    logos: ImageFile[];
    results: BrandingResult[];
    colors: string[];
    isGenerating: boolean;
    isUploading: boolean;
    isAnalyzing: boolean;
    aspectRatio: AspectRatio;
    error: string | null;
}

export interface PlanIdea {
    id: string;
    tov: string;
    caption: string;
    schedule: string;
    scenario: string;
    image: ImageFile | null;
    isLoadingImage: boolean;
    imageError: string | null;
}

export interface PlanStudioProject extends ProjectBase {
    productImages: ImageFile[];
    prompt: string;
    targetMarket: string;
    dialect: string;
    ideas: PlanIdea[];
    isGeneratingPlan: boolean;
    isUploading: boolean;
    categoryAnalysis: string | null;
    isAnalyzingCategory: boolean;
    error: string | null;
}

export interface LocalText {
    id: string;
    content: string;
    fontSize: number;
    color: string;
    fontFamily: string;
    fontWeight: string;
    x: number;
    y: number;
    isVisible: boolean;
    rotation: number;
    letterSpacing: number;
    lineHeight: number;
    maxWidth: number;
}

export interface EditAdjustments {
    sharpness: number;
    lut: string;
}

export interface GlobalLayer {
    id: string;
    file: ImageFile;
    scale: number;
    x: number;
    y: number;
}

export interface EditStudioProject extends ProjectBase {
    baseImages: ImageFile[];
    localTexts: { [key: number]: LocalText[] };
    committedTexts: { [key: number]: LocalText[] };
    globalLayers: GlobalLayer[];
    adjustments: EditAdjustments;
    isUploading: boolean;
}

export interface CopywriterStudioProject extends ProjectBase {
    productName: string;
    features: string;
    targetAudience: string;
    results: Array<{ type: string; content: string }>;
    isGenerating: boolean;
    error: string | null;
}

export interface PromptStudioHistoryItem {
    image: ImageFile;
    instructions: string;
    generatedPrompt: string;
}

export interface PromptStudioProject extends ProjectBase {
    images: ImageFile[];
    instructions: string;
    generatedPrompt: string | null;
    history: PromptStudioHistoryItem[];
    isLoading: boolean;
    isUploading: boolean;
    error: string | null;
}

export interface VoiceOverHistoryItem {
    audio: AudioFile;
    text: string;
    style: string;
    voice: string;
}

export interface VoiceOverStudioProject extends ProjectBase {
    text: string;
    styleInstructions: string;
    selectedVoice: string;
    voiceGenderFilter: 'All' | 'Male' | 'Female';
    generatedAudio: AudioFile | null;
    history: VoiceOverHistoryItem[];
    isLoading: boolean;
    isPlaying: boolean;
    previewLoadingVoice: string | null;
    previewPlayingVoice: string | null;
    error: string | null;
}

export type ControlCategory = 'Face' | 'Head' | 'Body' | 'Retouch';

export interface ControllerSlider {
    id: string;
    label: string;
    value: number;
    min: number;
    max: number;
    step: number;
    category: ControlCategory;
}

export interface ControllerStudioProject extends ProjectBase {
    sourceImages: ImageFile[];
    generatedImage: ImageFile | null;
    sliders: ControllerSlider[];
    activeCategory: ControlCategory;
    isGenerating: boolean;
    isUploading: boolean;
    history: HistoryItem[];
    error: string | null;
}

export interface CampaignStudioProject extends ProjectBase {
    productImages: ImageFile[];
    productAnalysis: string | null;
    isAnalyzing: boolean;
    selectedMood: string;
    customPrompt: string;
    customIdeas: string[];
    mode: 'auto' | 'custom';
    results: Array<{
        scenario: string;
        image: ImageFile | null;
        isLoading: boolean;
        isEditing: boolean;
        error: string | null;
        editPrompt: string;
    }>;
    isGenerating: boolean;
    isUploading: boolean;
    error: string | null;
}

// الأجنحة المدمجة الجديدة لتبسيط الواجهة
export type AppSuite = 
    | 'power'
    | 'photography'
    | 'marketing'
    | 'av_media'
    | 'design'
    | 'ai_lab';

export type AppView = 
    | 'landing'
    | 'faq'
    | 'suite_view'
    | AppSuite
    | 'privacy_policy'
    | 'terms_of_service'
    | 'admin_dashboard';
