
export interface ImageFile {
  base64: string;
  mimeType: string;
  name: string;
}

export interface AudioFile {
  base64: string;
  name: string;
}

export interface SavedAsset {
  id: string;
  user_id: string;
  asset_type: string;
  url: string;
  config: any;
  created_at: string;
}

export interface ProjectBase {
  id: string;
  name: string;
}

export type AppView =
  | 'landing' | 'dashboard' | 'daily_pack' | 'photoshoot' | 'video_studio' | 'plan_studio'
  | 'branding_mockups' | 'strategy_engine' | 'trend_engine' | 'brand_kit' | 'pricing'
  | 'library' | 'auth' | 'suite_view' | 'power' | 'ads_studio' | 'faq' | 'privacy_policy' | 'terms_of_service'
  | 'admin' | 'performance_studio' | 'content_library' | 'storyboard_studio'
  | 'market_intelligence_hub' | 'campaign_builder_hub' | 'creative_studio_hub' | 'launch_brief_hub' | 'voiceover_studio' | 'dynamic_ads' | 'pro_mode';

export interface EliteChatMessage {
  role: 'user' | 'bot';
  text: string;
}

export interface MasterFactoryProject extends ProjectBase {
  activeMode: 'guided' | 'machine' | 'transformer';
  // Guided Mode
  messages: EliteChatMessage[];
  step: number;
  currentTone: 'CLASSIC' | 'FUNNY' | 'UGC';
  // Machine Mode
  productInfo: { product: string; target: string; goals: string };
  topicIdeas: string[];
  // Transformer Mode
  rawInput: string;
  // Shared
  finalScript: string | null;
  isGenerating: boolean;
  error: string | null;
}

export interface UGCScriptProject extends ProjectBase {
  who: string; teaches: string; toWhom: string; painPoints: string; results: string; cta: string; avatarDescription: string;
  achievesWhat: string; productSelling: string; customerPains: string; desiredOutcome: string; targetAction: string; topicIdeas: string[]; selectedTopic: string;
  originalScriptInput: string; transformedUGCScript: string | null;
  finalScript: string | null; scriptType: 'reel' | 'youtube' | 'transformed_ugc';
  activeMode: 'avatar' | 'machine' | 'transformer';
  isGenerating: boolean; error: string | null;
}

export interface DailyPackProject extends ProjectBase {
  productImages: ImageFile[];
  description: string;
  tone: string;
  isGenerating: boolean;
  progress: number;
  result: any | null;
}

export interface PlanIdea {
  id: string; tov: string; caption: string; schedule: string; scenario: string; image: ImageFile | null; isLoadingImage: boolean; imageError: string | null; visualPrompt?: string; prompt?: string;
}

export interface PlanStudioProject extends ProjectBase {
  productImages: ImageFile[]; prompt: string; targetMarket: string; dialect: string; ideas: PlanIdea[]; categoryAnalysis: string | null; isGeneratingPlan: boolean; isAnalyzingCategory: boolean; isUploading: boolean; error: string | null;
}

export interface BrandKit {
  logo: ImageFile | null; colors: string[]; brandName: string; industry: string;
}

export type LightingStyle = 'Natural Light' | 'Studio Light' | 'Golden Hour' | 'Blue Hour' | 'Cinematic' | 'Dramatic';
export type CameraPerspective = 'Front View' | 'Top View' | 'Side View' | '45° Angle' | 'Close-up' | 'Macro Shot';
export type AspectRatio = '16:9' | '9:16' | '4:3' | '3:4' | '1:1';

export interface CustomizationOptions {
  lightingStyle: LightingStyle;
  cameraPerspective: CameraPerspective;
}

export interface HistoryItem {
  image: ImageFile;
  prompt: string;
}

export interface CreatorStudioProject extends ProjectBase {
  productImages: ImageFile[]; styleImages: ImageFile[]; prompt: string; options: CustomizationOptions; isPromptAutoGenerated: boolean; isLoading: boolean; error: string | null; generatedImage: ImageFile | null; history: HistoryItem[]; uploadingTarget: 'product' | 'style' | null;
}

export interface PhotoshootResult {
  shotType: string; image: ImageFile | null; isLoading: boolean; error: string | null; isEditing: boolean;
}

export interface PhotoshootDirectorProject extends ProjectBase {
  productImages: ImageFile[]; selectedShotTypes: string[]; customStylePrompt: string; isGenerating: boolean; error: string | null; results: PhotoshootResult[];
}

export interface BrandingResult {
  category: string; image: ImageFile | null; isLoading: boolean; error: string | null; editPrompt: string; isEditing: boolean;
}

export interface BrandingStudioProject extends ProjectBase {
  logos: ImageFile[]; isAnalyzing: boolean; isGenerating: boolean; isUploading: boolean; error: string | null; results: BrandingResult[]; aspectRatio: AspectRatio; colors: string[];
}

export interface MarketingStudioProject extends ProjectBase {
  brandType: 'new' | 'existing'; brandName: string; specialty: string; brief: string; websiteLink: string; language: 'ar' | 'en'; isGenerating: boolean; result: string | null; error: string | null;
}

export interface StoryboardScene {
  id: string; description: string; visualPrompt: string; cameraAngle: string; dialogue?: string; image: ImageFile | null; videoUrl: string | null; isLoading: boolean; isVideoLoading: boolean; error: string | null;
}

export interface StoryboardStudioProject extends ProjectBase {
  subjectImages: ImageFile[]; customInstructions: string; isUploading: boolean; isGeneratingPlan: boolean; error: string | null; scenes: StoryboardScene[]; gridImage: ImageFile | null; aspectRatio: AspectRatio;
}

export interface TrendItem {
  topic: string; relevance: string; contentIdea: string; viralHook: string;
}

export interface TrendEngineProject extends ProjectBase {
  region: string; niche: string; isGenerating: boolean; error: string | null; results: TrendItem[];
}

// Added missing exports for component type definitions

export type ControlCategory = 'Face' | 'Retouch';

export interface ControllerSlider {
  id: string;
  label: string;
  value: number;
  min: number;
  max: number;
  step: number;
  category: ControlCategory;
}

export interface PowerStudioResult {
  analysis: string;
  visualPrompt: string;
  fbAds: {
    primaryText: string;
    headline: string;
  };
  visual: ImageFile;
  marketAnalysis?: any;
  personas?: any[];
  swot?: any;
  valueProp?: any;
  channelPlan?: any;
  contentPlan?: any;
}

export type ShotType = string;

export interface PromptStudioHistoryItem {
  image: ImageFile;
  instructions: string;
  generatedPrompt: string;
}

export interface PromptStudioProject extends ProjectBase {
  images: ImageFile[];
  instructions: string;
  isUploading: boolean;
  isLoading: boolean;
  error: string | null;
  generatedPrompt: string | null;
  history: PromptStudioHistoryItem[];
}

export interface VoiceOverHistoryItem {
  audio: AudioFile;
  text: string;
  style: string;
  voice: string;
}

export interface VoiceOverStudioProject extends ProjectBase {
  text: string;
  styleInstructions: string;
  selectedVoice: string;
  isLoading: boolean;
  isPlaying: boolean;
  error: string | null;
  generatedAudio: AudioFile | null;
  history: VoiceOverHistoryItem[];
}

export interface ControllerStudioProject extends ProjectBase {
  sourceImages: ImageFile[];
  generatedImage: ImageFile | null;
  isUploading: boolean;
  isGenerating: boolean;
  error: string | null;
  sliders: ControllerSlider[];
  history: HistoryItem[];
}

export interface CampaignResult {
  scenario: string;
  image: ImageFile | null;
  isLoading?: boolean;
  isEditing?: boolean;
  error?: string | null;
  editPrompt?: string;
}

export interface CampaignStudioProject extends ProjectBase {
  productImages: ImageFile[];
  mode: 'auto' | 'custom';
  selectedMood: string;
  customPrompt: string;
  customIdeas: string[];
  isUploading: boolean;
  isGenerating: boolean;
  isAnalyzing: boolean;
  productAnalysis: string | null;
  results: CampaignResult[];
  error: string | null;
}

export interface EditAdjustments {
  lut: string;
  sharpness: number;
}

export interface LocalText {
  id: string;
  content: string;
  fontSize: number;
  color: string;
  fontFamily: string;
  fontWeight: string;
  x: number;
  y: number;
  isVisible: boolean;
  rotation: number;
  letterSpacing: number;
  lineHeight: number;
  maxWidth: number;
}

export interface GlobalLayer {
  id: string;
  type: 'text' | 'image';
}

export interface EditStudioProject extends ProjectBase {
  baseImages: ImageFile[];
  isUploading: boolean;
  adjustments: EditAdjustments;
  localTexts: { [slotIdx: number]: LocalText[] };
}

export interface PowerStudioProject extends ProjectBase {
  brandName: string;
  productCategory: string;
  productDescription: string;
  productImages: ImageFile[];
  goal: string;
  targetMarket: string;
  dialect: string;
  isGenerating: boolean;
  progress: number;
  currentStep: string;
  result: PowerStudioResult | null;
  error: string | null;
}

export interface UGCStudioProject extends ProjectBase {
  productImages: ImageFile[];
  selectedScenarios: string[];
  isUploading: boolean;
  isGenerating: boolean;
  results: BrandingResult[];
  error: string | null;
}

export interface InfluencerResult {
  id: string;
  image: ImageFile | null;
  isLoading: boolean;
  persona: string;
  error: string | null;
}

export interface InfluencerStudioProject extends ProjectBase {
  productImages: ImageFile[];
  selectedPersonas: string[];
  isUploading: boolean;
  isGenerating: boolean;
  results: InfluencerResult[];
}

export interface VideoJob {
  id: string;
  product_name: string;
  status: 'pending' | 'scripting' | 'voicing' | 'rendering' | 'completed' | 'failed';
  script?: string;
  video_url?: string;
  created_at: string;
}

export interface AdsStudioProject extends ProjectBase {
  productName: string;
  benefits: string;
  price: string;
  language: 'ar' | 'en';
  template: 'ugc' | 'classic';
  isGenerating: boolean;
  currentStep: string;
  jobs: VideoJob[];
  error: string | null;
}

export interface PerformanceStudioProject extends ProjectBase {
  targetMarket: string;
  campaignGoal: string;
  dialect: string;
  platform: string;
  productDescription: string;
  sellingPrice: string;
  brandTone: string;
  referenceImage: ImageFile | null;
  isGenerating: boolean;
  isGeneratingFull: boolean;
  result: {
    strategicIntelligence: {
      productType: string;
      riskLevel: string;
      emotionalDriver: string;
      archetype: string;
      psychologicalTrigger: string;
      biggestObjection: string;
    };
    creativeStrategyMatrix: {
      angles: {
        title: string;
        trigger: string;
        principle: string;
        marketReason: string;
        objectionNeutralizer: string;
        rank: number;
        isRecommended: boolean;
      }[];
      recommendationReason: string;
    };
    launchPack: {
      hooks: string[];
      adCopy: string;
      ugcScript: string;
      offerStructure: string;
      upsellSuggestion: string;
      cta: string;
      testingHooks: string[];
    };
    visualMatchingEngine: {
      imageConcepts: {
        description: string;
        angle: string;
        emotion: string;
        lighting: string;
        why: string;
      }[];
      thumbnailConcept: string;
      storyboard: {
        frame: number;
        scene: string;
        shot: string;
        movement: string;
        text: string;
        purpose: string;
      }[];
    };
    profitBrain: {
      valueStacking: string;
      aovIncrease: string;
      scarcityUrgency: string;
      riskReversal: string;
    };
    performanceSimulation: {
      hookStrength: 'Low' | 'Medium' | 'High';
      conversionConfidence: number;
      riskLevel: string;
      testingStructure: string;
    };
  } | null;
  fullCampaign: {
    adSets: {
      angle: string;
      visualPrompt: string;
      storyboard: any[];
      image?: string;
    }[];
  } | null;
  error: string | null;
}

export interface ProductionFactoryProject extends ProjectBase {
  activeCampaignId: string | null;
  jobs: VideoJob[];
  isGenerating: boolean;
  error: string | null;
}

export interface VoiceStudioProject extends ProjectBase {
  text: string;
  voiceId: string;
  dialect: string;
  isGenerating: boolean;
  resultAudioUrl: string | null;
  error: string | null;
}

export interface EliteScriptProject extends ProjectBase {
  currentMode: string;
  messages: EliteChatMessage[];
  isGenerating: boolean;
  step: number;
  error: string | null;
}

export interface DynamicPromptStyle {
  id: number;
  styleName: string;
  styleDescription: string;
  dynamicPrompt: string;
  requiredVariables: string[];
}

export interface DynamicAdsResult {
  id: string;
  styleName: string;
  image: ImageFile | null;
  isLoading: boolean;
  error: string | null;
}

export interface DynamicAdsStudioProject extends ProjectBase {
  productImages: ImageFile[];
  selectedStyleId: number | null;
  autoFillDescription: string;
  variableValues: Record<string, string>;
  isGenerating: boolean;
  isUploading: boolean;
  isAutoFilling: boolean;
  error: string | null;
  results: DynamicAdsResult[];
}
