
import React, { useEffect, useRef, useCallback } from 'react';
import { CreatorStudioProject, ImageFile } from '../types';
/* Fix: removed non-existent translateText from imports */
import { analyzeStyleImage, generateImage, editImage } from '../services/geminiService';
import { resizeImage } from '../utils';
import { deductCredits, CREDIT_COSTS } from '../lib/supabase';
import CustomizationPanel from './CustomizationPanel';
import ImageWorkspace from './ImageWorkspace';
import PromptEditor from './PromptEditor';
import HistoryPanel from './HistoryPanel';
import ResultDisplay from './ResultDisplay';

interface CreatorStudioProps {
  project: CreatorStudioProject;
  setProject: React.Dispatch<React.SetStateAction<CreatorStudioProject>>;
  userId?: string;
  refreshCredits?: () => void;
}

const CreatorStudio: React.FC<CreatorStudioProps> = ({
  project,
  setProject,
  userId,
  refreshCredits
}) => {
  
  const translateTimeoutRef = useRef<number | null>(null);
  const translationRequestCounter = useRef(0);

  const updateActiveProjectState = useCallback((updater: (projectDraft: CreatorStudioProject) => void) => {
    setProject(currentProject => {
      const projectToUpdate = { ...currentProject };
      updater(projectToUpdate);
      return projectToUpdate;
    });
  }, [setProject]);

  const handleGenerate = useCallback(async () => {
    if (!project || !project.prompt) {
      updateActiveProjectState(p => { p.error = 'فضلاً اكتب وصفاً للصورة أو اختر وضعاً معيناً.'; });
      return;
    }

    if (!userId) return;

    updateActiveProjectState(p => { p.isLoading = true; p.error = null; p.generatedImage = null; });

    try {
      const result = await generateImage(project.productImages, project.prompt, project.styleImages);
      /* Fix: Changed IMAGE_GEN to IMAGE_PRO as per lib/supabase.ts definition */
      const deducted = await deductCredits(userId, CREDIT_COSTS.IMAGE_PRO);
      
      if (deducted) {
        updateActiveProjectState(p => {
            p.generatedImage = result;
            p.history = [{ image: result, prompt: project.prompt }, ...p.history];
        });
        if (refreshCredits) refreshCredits();
      } else {
        /* Fix: Changed IMAGE_GEN to IMAGE_PRO */
        updateActiveProjectState(p => { p.error = `رصيدك غير كافٍ. تكلفة توليد هذه الصورة هي ${CREDIT_COSTS.IMAGE_PRO} نقاط.`; });
      }
    } catch (err) {
      console.error(err);
      updateActiveProjectState(p => { p.error = err instanceof Error ? err.message : 'فشلت عملية التوليد.'; });
    } finally {
      updateActiveProjectState(p => { p.isLoading = false; });
    }
  }, [project, userId, updateActiveProjectState, refreshCredits]);

  useEffect(() => {
    if (project?.styleImages?.length > 0 && !project.styleDescription && !project.isAnalyzingStyle && !project.error) {
      const getStyleDescription = async () => {
        updateActiveProjectState(p => { 
          p.isAnalyzingStyle = true;
          p.error = null;
        });
        try {
          const description = await analyzeStyleImage(project.styleImages);
          updateActiveProjectState(p => { p.styleDescription = description; });
        } catch (err) {
          updateActiveProjectState(p => {
            p.error = err instanceof Error ? err.message : "Could not analyze the style image.";
            p.styleDescription = null;
          });
        } finally {
          updateActiveProjectState(p => { p.isAnalyzingStyle = false; });
        }
      };
      getStyleDescription();
    }
  }, [project?.styleImages, project?.styleDescription, updateActiveProjectState]);

  useEffect(() => {
    if (!project || !project.isPromptAutoGenerated) return;
    const { productImages, options, styleDescription } = project;
    if (productImages.length === 0) return;

    let newPrompt = `Professional high-end commercial photograph of the product. Lighting: ${options.lightingStyle}. Angle: ${options.cameraPerspective}. ${styleDescription ? `Inspired by: ${styleDescription}` : ''} Render in 8k, photorealistic.`;
    if(project.prompt === '') updateActiveProjectState(p => { p.prompt = newPrompt; });
  }, [project?.isPromptAutoGenerated, project?.productImages, project?.options, project?.styleDescription, updateActiveProjectState]);

  const handleFileUpload = (updater: (files: ImageFile[]) => void, target: 'product' | 'style') => async (files: File[]) => {
      if (!files || files.length === 0) return;
      updateActiveProjectState(p => { p.uploadingTarget = target; p.error = null; });
      try {
          const resizedFile = await resizeImage(files[0], 2048, 2048);
          const reader = new FileReader();
          reader.onloadend = () => {
              updater([{ base64: (reader.result as string).split(',')[1], mimeType: resizedFile.type, name: resizedFile.name }]);
          };
          reader.readAsDataURL(resizedFile);
      } catch (err) { console.error(err); }
      finally { updateActiveProjectState(p => { p.uploadingTarget = null; }); }
  };

  return (
    <main className="w-full grid grid-cols-1 lg:grid-cols-2 gap-8 pt-4 pb-12 items-start">
        <div className="flex flex-col gap-6 order-1">
            <div className="grid grid-cols-2 gap-4">
                <div className="glass-card p-3 rounded-2xl flex flex-col gap-2 items-center border border-white/5">
                    <h3 className="text-[10px] font-black text-white/40 uppercase tracking-widest">صورة المنتج</h3>
                    <ImageWorkspace
                        id="creator-product-uploader"
                        images={project.productImages}
                        onImagesUpload={handleFileUpload(files => updateActiveProjectState(p => { p.productImages = files; }), 'product')}
                        onImageRemove={(idx) => updateActiveProjectState(p => { p.productImages = []; })}
                        isUploading={project.uploadingTarget === 'product'}
                    />
                </div>
                <div className="glass-card p-3 rounded-2xl flex flex-col gap-2 items-center border border-white/5">
                    <h3 className="text-[10px] font-black text-white/40 uppercase tracking-widest">مرجع التصميم</h3>
                    <ImageWorkspace 
                        id="creator-style-uploader"
                        title="Style Image"
                        images={project.styleImages}
                        onImagesUpload={handleFileUpload(files => updateActiveProjectState(p => { p.styleImages = files; p.styleDescription = null; }), 'style')}
                        onImageRemove={(idx) => updateActiveProjectState(p => { p.styleImages = []; p.styleDescription = null; })}
                        isUploading={project.uploadingTarget === 'style'}
                    />
                </div>
            </div>

            <CustomizationPanel options={project.options} setOptions={(opt) => updateActiveProjectState(p => { p.options = opt; })} />

            <PromptEditor
                prompt={project.prompt}
                setPrompt={(val) => updateActiveProjectState(p => { p.prompt = val; p.isPromptAutoGenerated = false; })}
                isAutoGenerated={project.isPromptAutoGenerated}
                onResetPrompt={() => updateActiveProjectState(p => { p.isPromptAutoGenerated = !p.isPromptAutoGenerated; })}
                translatedPrompt={null}
                isTranslating={false}
                onUseTranslation={() => {}}
            />

            <button
                onClick={handleGenerate}
                disabled={project.isLoading || !project.prompt || !!project.uploadingTarget}
                className="w-full bg-[var(--color-accent)] hover:bg-[var(--color-accent-dark)] text-white font-black py-5 rounded-2xl text-lg shadow-xl shadow-[var(--color-accent)]/20 transition-all active:scale-95 disabled:opacity-50 uppercase tracking-widest"
            >
                {/* Fix: Changed IMAGE_GEN to IMAGE_PRO */}
                {project.isLoading ? 'جاري توليد التصميم...' : `توليد الصورة (${CREDIT_COSTS.IMAGE_PRO} نقاط)`}
            </button>

            {project.error && <div className="bg-red-500/10 border border-red-500/20 text-red-400 px-4 py-3 rounded-xl text-xs font-bold text-center uppercase tracking-tight">{project.error}</div>}
        </div>

        <div className="flex flex-col gap-6 order-2">
             <div className="glass-card rounded-3xl p-6 min-h-[400px] border border-white/5 shadow-2xl">
                <ResultDisplay 
                    imageFile={project.generatedImage} 
                    isLoading={project.isLoading}
                />
             </div>
            <HistoryPanel history={project.history} onSelect={(img) => updateActiveProjectState(p => { p.generatedImage = img; })} />
        </div>
    </main>
  );
};

export default CreatorStudio;
