
import React from 'react';

interface PromptEditorProps {
  prompt: string;
  setPrompt: (prompt: string) => void;
  isAutoGenerated: boolean;
  onResetPrompt: () => void;
  onApplyVisionMode: (mode: 'fusion' | 'placement') => void;
}

const STOCK_COLORS = [
    { label: 'أبيض', hex: '#FFFFFF', tag: '[Pure White Rim Lighting]' },
    { label: 'أحمر', hex: '#FF3B30', tag: '[Dramatic Red Studio Backlight]' },
    { label: 'أزرق', hex: '#007AFF', tag: '[Cool Blue Cyberpunk Lighting]' },
    { label: 'ذهبي', hex: '#FFD700', tag: '[Warm Golden Hour Sunlight]' },
];

const PromptEditor: React.FC<PromptEditorProps> = ({ prompt, setPrompt, isAutoGenerated, onResetPrompt, onApplyVisionMode }) => {
  
  const addTag = (tag: string) => {
    if (!prompt.includes(tag)) {
        setPrompt(`${prompt} ${tag}`.trim());
    }
  };

  const handleModeSelection = (mode: 'fusion' | 'placement') => {
    let professionalPrompt = "";
    if (mode === 'fusion') {
        professionalPrompt = "Professional Style Fusion: Take the subject from the main image and seamlessly re-render it using the visual style, professional lighting, and artistic mood of the reference image. High-end commercial quality, 8k resolution, photorealistic. STRICTLY PRESERVE all original text, labels, and branding. DO NOT modify existing writing. NO EXTRA generated text in the scene.";
    } else {
        professionalPrompt = "Professional Scene Placement: Extract the subject from the main image and place it professionally into the exact environment, background, and spatial context of the reference image. Match the lighting, shadows, and perspective of the reference perfectly for a hyper-realistic result. STRICTLY PRESERVE all original text, labels, and branding. DO NOT modify existing writing. NO EXTRA generated text in the scene.";
    }
    // نقوم بحقن النص بالكامل بدلاً من إضافة تاغ فقط
    setPrompt(professionalPrompt);
    onApplyVisionMode(mode);
  };

  return (
    <div className="bg-white/5 rounded-3xl p-6 flex flex-col gap-5 shadow-sm border border-white/5 text-right font-tajawal">
      <div className="flex justify-between items-center flex-row-reverse">
        <h2 className="text-xl font-black text-white">وصف الرؤية الفنية</h2>
        <button onClick={onResetPrompt} className={`text-[10px] px-4 py-2 rounded-xl transition-all font-black uppercase tracking-widest ${isAutoGenerated ? 'bg-[#FFD700] text-black shadow-lg shadow-[#FFD700]/20' : 'bg-white/5 text-slate-400 hover:text-[#FFD700]'}`}>
            {isAutoGenerated ? '✨ ذكاء نشط' : 'توليد تلقائي'}
        </button>
      </div>
      
       <textarea 
        value={prompt} 
        onChange={(e) => setPrompt(e.target.value)} 
        rows={6} 
        className="w-full bg-black/40 border border-white/10 rounded-2xl p-5 text-sm font-bold text-white focus:border-[#FFD700] focus:bg-black/60 outline-none text-right transition-all leading-relaxed shadow-inner" 
        placeholder="صف المشهد الذي تتخيله أو اختر وضعاً احترافياً من الأسفل..." 
       />

      <div className="flex flex-col gap-4 pt-4 border-t border-white/5 items-end">
        <span className="text-[10px] font-black text-slate-400 uppercase tracking-[0.3em]">أوضاع الدمج الاحترافية</span>
        <div className="grid grid-cols-2 gap-4 w-full">
            <button 
                onClick={() => handleModeSelection('fusion')} 
                className="group p-4 bg-black/40 hover:bg-[#FFD700]/10 border border-white/10 hover:border-[#FFD700]/50 rounded-[1.5rem] text-right transition-all shadow-sm"
            >
                <div className="font-black text-white text-xs mb-1 group-hover:text-[#FFD700]">وضع الدمج (Style Fusion)</div>
                <div className="text-[9px] text-slate-400 font-bold leading-tight">تطبيق نمط الصورة المرجعية على منتجك.</div>
            </button>
            <button 
                onClick={() => handleModeSelection('placement')} 
                className="group p-4 bg-black/40 hover:bg-[#FFD700]/10 border border-white/10 hover:border-[#FFD700]/50 rounded-[1.5rem] text-right transition-all shadow-sm"
            >
                <div className="font-black text-white text-xs mb-1 group-hover:text-[#FFD700]">وضع الإسقاط (Placement)</div>
                <div className="text-[9px] text-slate-400 font-bold leading-tight">نقل المنتج لبيئة الصورة المرجعية.</div>
            </button>
        </div>

        <div className="flex flex-wrap gap-2 flex-row-reverse mt-2">
            <button onClick={() => addTag('[Studio Lighting]')} className="px-4 py-2 bg-white/5 hover:bg-white/10 text-slate-400 rounded-xl text-[10px] font-black transition-all">إضاءة استوديو</button>
            {STOCK_COLORS.map((c) => (
                <button key={c.label} onClick={() => addTag(c.tag)} className="flex items-center gap-2 px-3 py-2 bg-black/40 border border-white/10 rounded-full hover:border-[#FFD700]/50 transition-all shadow-sm">
                    <span className="text-[10px] font-bold text-slate-500">{c.label}</span>
                    <div className="w-2 h-2 rounded-full" style={{ backgroundColor: c.hex }}></div>
                </button>
            ))}
        </div>
      </div>
    </div>
  );
};

export default PromptEditor;