
import React from 'react';

interface PromptEditorProps {
  prompt: string;
  setPrompt: (prompt: string) => void;
  isAutoGenerated: boolean;
  onResetPrompt: () => void;
  translatedPrompt: string | null;
  isTranslating: boolean;
  onUseTranslation: (translatedText: string) => void;
  onApplyStockBase?: () => void;
  onApplyRimColor?: (color: string) => void;
  onApplyVisionMode?: (mode: 'fusion' | 'placement') => void;
}

const SparkleIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 mr-2" viewBox="0 0 20 20" fill="currentColor">
        <path fillRule="evenodd" d="M5 2a1 1 0 011 1v1h1a1 1 0 010 2H6v1a1 1 0 11-2 0V6H3a1 1 0 110-2h1V3a1 1 0 011-1zm12 10a1 1 0 011 1v1h1a1 1 0 110 2h-1v1a1 1 0 11-2 0v-1h-1a1 1 0 110-2h1v-1a1 1 0 011-1zM10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm0 14a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM4.156 5.156a1 1 0 011.414-1.414l.707.707a1 1 0 01-1.414 1.414l-.707-.707zm11.314 11.314a1 1 0 011.414-1.414l.707.707a1 1 0 01-1.414 1.414l-.707-.707zm-8.485 2.122a1 1 0 01-1.414 1.414l-.707-.707a1 1 0 011.414-1.414l.707.707zM15.844 5.156a1 1 0 011.414 1.414l-.707.707a1 1 0 01-1.414-1.414l.707-.707z" clipRule="evenodd" />
    </svg>
);

const TrashIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 mr-1.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
    </svg>
);

const MagicIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a2 2 0 00-1.96 1.414l-.477 2.387a2 2 0 001.414 2.333l2.387.477a2 2 0 002.333-1.414l.477-2.387a2 2 0 00-1.76-2.387zM5.572 15.428a2 2 0 011.022-.547l2.387-.477a2 2 0 011.96 1.414l.477 2.387a2 2 0 01-1.414 2.333l-2.387.477a2 2 0 01-2.333-1.414l-.477-2.387a2 2 0 011.76-2.387zM12.5 5.5a3 3 0 11-6 0 3 3 0 016 0zM19.5 5.5a3 3 0 11-6 0 3 3 0 016 0z" />
    </svg>
);

const STOCK_COLORS = [
    { label: 'أبيض', hex: '#FFFFFF', text: 'white' },
    { label: 'أحمر', hex: '#FF3B30', text: 'red' },
    { label: 'أزرق', hex: '#007AFF', text: 'blue' },
    { label: 'ذهبي', hex: '#FFD700', text: 'gold' },
    { label: 'سيان', hex: '#32ADE6', text: 'cyan' },
    { label: 'وردي', hex: '#FF2D55', text: 'pink' },
    { label: 'أخضر', hex: '#34C759', text: 'lime' },
];

const PromptEditor: React.FC<PromptEditorProps> = ({ 
  prompt, setPrompt, isAutoGenerated, onResetPrompt, translatedPrompt, isTranslating, onUseTranslation, onApplyStockBase, onApplyRimColor, onApplyVisionMode 
}) => {
  return (
    <div className="glass-card rounded-2xl p-5 flex flex-col gap-4 shadow-xl border border-white/5 text-right">
      <div className="flex justify-between items-center">
        <h2 className="text-lg font-black text-[var(--color-text-base)] uppercase tracking-tight">أوامر الرؤية الذكية</h2>
        <div className="flex gap-2">
            <button onClick={() => setPrompt('')} className="flex items-center text-[10px] px-3 py-2 rounded-lg bg-red-500/10 hover:bg-red-500/20 text-red-400 hover:text-red-300 transition-all font-black uppercase tracking-widest" title="مسح النص">
                <TrashIcon /> مسح
            </button>
            <button onClick={onResetPrompt} className={`flex items-center text-[10px] px-3 py-2 rounded-lg transition-all font-black uppercase tracking-widest ${isAutoGenerated ? 'bg-[var(--color-accent)] text-white shadow-lg' : 'bg-white/5 hover:bg-white/10 text-[var(--color-accent-light)]'}`}>
                <SparkleIcon /> {isAutoGenerated ? 'تلقائي نشط' : 'تفعيل التلقائي'}
            </button>
        </div>
      </div>
       <textarea value={prompt} onChange={(e) => setPrompt(e.target.value)} rows={5} className="w-full glass-input rounded-xl p-4 text-sm leading-relaxed transition-all focus:ring-1 focus:ring-[var(--color-accent)] font-medium suggestions-scrollbar text-right" placeholder="صف رؤيتك هنا باللغة العربية أو الإنجليزية..." />

      <div className="flex flex-col gap-4 pt-3 border-t border-white/5">
        <div className="flex flex-col gap-2">
            <span className="text-[10px] font-black text-[var(--color-accent)] uppercase tracking-[0.2em] ml-1 flex items-center justify-end gap-2">
                أنماط إبداعية احترافية <MagicIcon />
            </span>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <button onClick={() => onApplyVisionMode?.('fusion')} className="flex flex-col items-end gap-1 p-3 bg-black/40 hover:bg-black/60 border border-white/10 hover:border-emerald-500/50 rounded-xl transition-all group">
                    <div className="flex items-center gap-2">
                        <span className="text-[10px] font-black text-white uppercase tracking-wider">وضع الدمج (Style Fusion)</span>
                        <div className="w-2 h-2 bg-emerald-500 rounded-full animate-pulse"></div>
                    </div>
                    <span className="text-[9px] text-white/40 group-hover:text-white/70 text-right">دمج المنتج مع نمط وإضاءة الصورة المرجعية.</span>
                </button>
                <button onClick={() => onApplyVisionMode?.('placement')} className="flex flex-col items-end gap-1 p-3 bg-black/40 hover:bg-black/60 border border-white/10 hover:border-blue-500/50 rounded-xl transition-all group">
                    <div className="flex items-center gap-2">
                        <span className="text-[10px] font-black text-white uppercase tracking-wider">وضع الإسقاط (Scene Placement)</span>
                        <div className="w-2 h-2 bg-blue-500 rounded-full animate-pulse"></div>
                    </div>
                    <span className="text-[9px] text-white/40 group-hover:text-white/70 text-right">وضع المنتج داخل بيئة الصورة المرجعية تماماً.</span>
                </button>
            </div>
        </div>

        <div className="flex flex-col gap-2 pt-2 border-t border-white/5 items-end">
            <span className="text-[9px] font-black text-white/30 uppercase tracking-widest ml-1">إضاءة استوديو جاهزة</span>
            <div className="flex items-center gap-2 flex-wrap flex-row-reverse">
                <button onClick={onApplyStockBase} className="px-3 py-1.5 bg-white/5 hover:bg-white/10 border border-white/10 rounded-lg text-[9px] font-black text-white/60 uppercase transition-all">إضاءة أساسية</button>
                <div className="h-4 w-px bg-white/10 mx-1"></div>
                <div className="flex flex-wrap gap-1.5 flex-row-reverse">
                    {STOCK_COLORS.map((color) => (
                        <button key={color.label} onClick={() => onApplyRimColor?.(color.text)} className="group flex items-center gap-1.5 px-2.5 py-1.5 bg-black/40 hover:bg-black/60 border border-white/5 hover:border-[var(--color-accent)]/50 rounded-full transition-all" title={`إضاءة ${color.label}`}>
                            <span className="text-[9px] font-bold text-white/40 group-hover:text-white uppercase">{color.label}</span>
                            <div className="w-2 h-2 rounded-full" style={{ backgroundColor: color.hex, boxShadow: `0 0 6px ${color.hex}66` }}></div>
                        </button>
                    ))}
                </div>
            </div>
        </div>
      </div>
    </div>
  );
};

export default PromptEditor;
